// SPDX-License-Identifier: LicenseRef-CASU-AntiCapitalist-1.4
// Byte-parity tests for the EPG module (apps/mpcasu/epg.cpp) against the
// Python reference casu/epg.py. Fixtures + canonical reference dumps are
// generated by the reference implementation; both sides must produce
// IDENTICAL sorted compact JSON.
#include "epg.hpp"

#include "casu/json.hpp"
#include "casu/sha256.hpp"

#include <QFile>
#include <cstdio>
#include <fstream>
#include <sstream>

using namespace mpcasu;
using casu::JsonValue;

namespace {

std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

QByteArray read_bytes(const QString& path) {
    QFile f(path);
    if (!f.open(QIODevice::ReadOnly)) return {};
    return f.readAll();
}

JsonValue to_json(const QString& s) { return JsonValue(s.toStdString()); }

JsonValue catalog_json(const StreamCatalog& cat) {
    auto root = std::make_shared<casu::JsonObject>();
    auto channels = std::make_shared<casu::JsonArray>();
    for (const StreamChannel& c : cat.channels) {
        auto o = std::make_shared<casu::JsonObject>();
        o->items["url"] = to_json(c.url);
        o->items["name"] = to_json(c.name);
        o->items["epg_id"] = to_json(c.epg_id);
        o->items["group"] = to_json(c.group);
        o->items["logo"] = to_json(c.logo);
        channels->items.push_back(JsonValue(std::move(o)));
    }
    root->items["channels"] = JsonValue(std::move(channels));
    auto urls = std::make_shared<casu::JsonArray>();
    for (const QString& u : cat.epg_urls)
        urls->items.push_back(to_json(u));
    root->items["epg_urls"] = JsonValue(std::move(urls));
    return JsonValue(std::move(root));
}

JsonValue guide_json(const EpgGuide& guide) {
    auto root = std::make_shared<casu::JsonObject>();
    auto names = std::make_shared<casu::JsonObject>();
    // Sorted iteration for deterministic dump (map is sorted anyway).
    std::map<std::string, std::string> names_sorted;
    for (auto it = guide.channel_names.constBegin();
         it != guide.channel_names.constEnd(); ++it)
        names_sorted[it.key().toStdString()] = it.value().toStdString();
    for (const auto& [k, v] : names_sorted) names->items[k] = JsonValue(v);
    root->items["channel_names"] = JsonValue(std::move(names));
    auto progs = std::make_shared<casu::JsonArray>();
    for (const Programme& p : guide.programmes) {
        auto o = std::make_shared<casu::JsonObject>();
        o->items["channel_id"] = to_json(p.channel_id);
        o->items["start_ms"] = JsonValue(p.start_ms);
        o->items["stop_ms"] = JsonValue(p.stop_ms);
        o->items["title"] = to_json(p.title);
        o->items["description"] = to_json(p.description);
        o->items["category"] = to_json(p.category);
        progs->items.push_back(JsonValue(std::move(o)));
    }
    root->items["programmes"] = JsonValue(std::move(progs));
    return JsonValue(std::move(root));
}

int failures = 0;

void check(bool ok, const char* label) {
    if (!ok) {
        ++failures;
        std::printf("FAIL %s\n", label);
    } else {
        std::printf("ok   %s\n", label);
    }
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::printf("usage: casu_epg_parity_test <fixture_dir>\n");
        return 2;
    }
    const std::string dir = argv[1];

    // --- M3U -----------------------------------------------------------------
    StreamCatalog catalog;
    const QString m3u_err =
        parse_m3u(read_bytes(QString::fromStdString(dir + "/epg_channels.m3u")),
                  QStringLiteral("/base/dir"), &catalog);
    check(m3u_err.isEmpty(), "m3u parses cleanly");
    const JsonValue mine_m3u = catalog_json(catalog);
    const JsonValue ref_m3u = casu::parse_json(read_file(dir + "/ref_m3u.json"));
    const std::string mine_dump = casu::dump_json(mine_m3u, true, false);
    const std::string ref_dump = casu::dump_json(ref_m3u, true, false);
    if (mine_dump != ref_dump) {
        for (std::size_t i = 0;
             i < std::min(mine_dump.size(), ref_dump.size()); ++i) {
            if (mine_dump[i] != ref_dump[i]) {
                std::printf("  m3u first diff at %zu: cpp=%c py=%c\n", i,
                            mine_dump[i], ref_dump[i]);
                break;
            }
        }
    }
    check(mine_dump == ref_dump, "m3u catalog IDENTICAL to reference");

    // --- XMLTV ---------------------------------------------------------------
    EpgGuide guide;
    const QString xml_err =
        parse_xmltv_guide(read_bytes(QString::fromStdString(dir + "/epg_guide.xmltv")),
                          &guide);
    check(xml_err.isEmpty(), "xmltv parses cleanly");
    const JsonValue mine_xml = guide_json(guide);
    const JsonValue ref_xml = casu::parse_json(read_file(dir + "/ref_xmltv.json"));
    const std::string mine_xml_dump = casu::dump_json(mine_xml, true, false);
    const std::string ref_xml_dump = casu::dump_json(ref_xml, true, false);
    if (mine_xml_dump != ref_xml_dump) {
        for (std::size_t i = 0; i < std::min(mine_xml_dump.size(),
                                             ref_xml_dump.size());
             ++i) {
            if (mine_xml_dump[i] != ref_xml_dump[i]) {
                std::printf("  xmltv first diff at %zu\nCPP: %.140s\nPY : %.140s\n",
                            i,
                            mine_xml_dump.substr(i, 140).c_str(),
                            ref_xml_dump.substr(i, 140).c_str());
                break;
            }
        }
    }
    check(mine_xml_dump == ref_xml_dump, "xmltv guide IDENTICAL to reference");

    // Timezone semantics spot-check: +0200 -> 00:00 UTC.
    bool tz_ok = !guide.programmes.isEmpty() &&
                 guide.programmes.first().start_ms ==
                     INT64_C(1787356800000);
    check(tz_ok, "xmltv UTC offset conversion (+0200)");

    // stop<=start entry dropped (NEGATIV title absent).
    bool neg_absent = true;
    for (const Programme& p : guide.programmes)
        if (p.title.contains("NEGATIV")) neg_absent = false;
    check(neg_absent, "stop<=start programme dropped");

    // DTD rejection.
    {
        EpgGuide g;
        const QString err = parse_xmltv_guide(
            QByteArray("<!DOCTYPE tv [<!ENTITY x \"y\">]><tv></tv>"), &g);
        check(!err.isEmpty() && err.contains("DTD"),
              "DTD rejected");
    }

    if (failures == 0) std::printf("ALL PASS\n");
    return failures == 0 ? 0 : 1;
}
