// SPDX-License-Identifier: LicenseRef-CASU-AntiCapitalist-1.4
// Byte-parity tests for the CASUNAT2 C++ port against the Python reference.
//
// Fixtures (generated by tools/parity/gen_reference.py with the reference
// implementation):
//   gen1.casu — writer output, recovery_interval=32
//   gen2.casu — same content, recovery_interval=2
// The C++ test re-encodes the identical logical content and requires
// byte-identical files, reads/reconstructs the Python-written containers and
// verifies digests, and exercises recover/repair + fail-closed rejections.
#include "casu/native_v2.hpp"
#include "casu/sha256.hpp"
#include "casu/json.hpp"

#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

using namespace casu;

namespace {

int failures = 0;
int checks = 0;

void check(bool ok, const char* label) {
    ++checks;
    if (!ok) {
        ++failures;
        std::printf("FAIL %s\n", label);
    } else {
        std::printf("ok   %s\n", label);
    }
}

std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

void write_file(const std::string& path, const std::string& data) {
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out.write(data.data(), static_cast<std::streamsize>(data.size()));
}

std::vector<uint8_t> gray_plane(uint8_t fill) {
    return std::vector<uint8_t>(8 * 8, fill);
}

natv2::CanonicalFrame make_frame(uint8_t fill) {
    natv2::CanonicalPlane plane;
    plane.data = gray_plane(fill);
    plane.rows = 8;
    plane.cols = 8;
    plane.itemsize = 1;
    std::vector<natv2::CanonicalPlane> planes;
    planes.push_back(std::move(plane));
    std::map<std::string, std::string> color{{"color_range", "tv"}};
    return natv2::canonical_frame(std::move(planes), "gray8", color,
                                  std::make_optional(
                                      std::make_pair(int64_t(8), int64_t(8))));
}

JsonValue parity_manifest() {
    // Must serialize identically to the fixture generator's dict.
    JsonValue v = parse_strict_json(R"json({
      "format": "CASUNAT2",
      "version": 2,
      "streams": [
        {"stream_id": 1, "type": "video", "time_base": [1, 90000],
         "width": 8, "height": 8, "pix_fmt": "gray8"},
        {"stream_id": 2, "type": "audio", "time_base": [1, 48000],
         "sample_rate": 48000, "channels": 2},
        {"stream_id": 3, "type": "subtitle", "time_base": [1, 1000]}
      ]
    })json");
    return v;
}

std::vector<casunat2::Chunk> parity_chunks() {
    std::vector<casunat2::Chunk> chunks;
    casunat2::Chunk key;
    key.chunk_type = casunat2::VIDEO_KEY_STATE;
    key.stream_id = 1;
    key.pts = 0;
    key.payload = natv2::encode_key_state(make_frame(10));
    chunks.push_back(key);

    // Tile update 1: region (0,0,4,4) -> 0xEE on a frame of 10s.
    casunat2::Chunk t1;
    t1.chunk_type = casunat2::VIDEO_TILE_UPDATE;
    t1.stream_id = 1;
    t1.pts = 0;
    t1.payload = natv2::encode_tile_update(make_frame(0xEE), 0, 0, 4, 4, nullptr);
    chunks.push_back(t1);

    // Tile update 2: region (6,6,2,2) -> 0x42.
    casunat2::Chunk t2;
    t2.chunk_type = casunat2::VIDEO_TILE_UPDATE;
    t2.stream_id = 1;
    t2.pts = 0;
    t2.payload = natv2::encode_tile_update(make_frame(0x42), 6, 6, 2, 2, nullptr);
    chunks.push_back(t2);

    casunat2::Chunk audio;
    audio.chunk_type = casunat2::AUDIO_BLOCK;
    audio.stream_id = 2;
    audio.pts = 0;
    std::vector<uint8_t> pcm;
    for (int rep = 0; rep < 4; ++rep)
        for (int b = 0; b < 256; ++b) pcm.push_back(static_cast<uint8_t>(b));
    audio.payload = natv2::encode_audio_block(pcm, 0, 1, 48000, 48000, 2,
                                              "s16le", "stereo", 256);
    chunks.push_back(audio);

    casunat2::Chunk sub;
    sub.chunk_type = casunat2::SUBTITLE_PACKET;
    sub.stream_id = 3;
    sub.pts = 0;
    natv2::SubtitlePacket packet;
    packet.start_pts = 0;
    packet.end_pts = 500;
    packet.text = "Hello Parit\u00e4t";
    packet.language = "de";
    packet.format = "text";
    sub.payload = natv2::encode_subtitle_packet(packet);
    chunks.push_back(sub);

    casunat2::Chunk chapters;
    chapters.chunk_type = casunat2::CHAPTER_TABLE;
    chapters.stream_id = 0;
    chapters.pts = 0;
    std::vector<natv2::Chapter> chapter_list{
        {0, 1000, "Intro", "und"}, {1000, 2000, "Teil zwei", "und"}};
    chapters.payload = natv2::encode_chapter_table(chapter_list);
    chunks.push_back(chapters);
    return chunks;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::printf("usage: casu_natv2_parity_test <fixture_dir>\n");
        return 2;
    }
    const std::string dir = argv[1];
    const std::string gen1_path = dir + "/gen1.casu";
    const std::string gen2_path = dir + "/gen2.casu";

    // --- 1. Read the Python-written container with full validation --------
    bool read_ok = true;
    casunat2::Container c;
    try {
        c = casunat2::read_native_v2(gen1_path);
    } catch (const CasuError& exc) {
        read_ok = false;
        std::printf("  read error: %s\n", exc.what());
    }
    check(read_ok, "python file passes full semantic validation");
    check(c.chunks.size() == 12, "python chunk count is 12");
    check(c.integrity_verified, "python integrity verified");
    check(c.seek_entries.size() == 1 &&
              c.seek_entries[0].key_state_offset == 612 &&
              c.seek_entries[0].first_update_offset == 842 &&
              c.seek_entries[0].target_pts == 0 &&
              c.seek_entries[0].stream_id == 1,
          "python seek entry matches");

    // Reconstruction digest must equal the reference value.
    bool recon_ok = true;
    std::string recon_digest;
    try {
        const natv2::CanonicalFrame frame =
            casunat2::reconstruct_video(c, 1, 0);
        recon_digest = frame.digest();
    } catch (const CasuError& exc) {
        recon_ok = false;
        std::printf("  reconstruct error: %s\n", exc.what());
    }
    check(recon_ok && recon_digest ==
            "558cacc23a3818c928d4ffd1a098b5119eabb599dd726277d26229050568f4c8",
        "reconstructed video digest matches python");

    // Audio metadata fast path.
    bool meta_ok = false;
    try {
        for (std::size_t i = 0; i < c.chunks.size(); ++i) {
            if (c.chunks[i].chunk_type != casunat2::AUDIO_BLOCK) continue;
            const JsonValue meta =
                c.read_audio_block_meta_at(c.offsets[i]);
            const JsonValue* fmt = meta.find("sample_format");
            const JsonValue* channels = meta.find("channels");
            meta_ok = meta.is_object() && fmt && fmt->is_string() &&
                      fmt->as_string() == "s16le" && channels &&
                      channels->is_int() && channels->as_int() == 2;
        }
    } catch (const CasuError&) {
        meta_ok = false;
    }
    check(meta_ok, "audio metadata fast path works");

    // --- 2. C++ writer byte parity ----------------------------------------
    const std::vector<casunat2::Chunk> chunks = parity_chunks();
    const JsonValue manifest = parity_manifest();
    std::string mine1, mine2;
    bool write_ok = true;
    try {
        casunat2::write_native_v2(dir + "/cpp_gen1.casu", manifest, chunks, 32);
        casunat2::write_native_v2(dir + "/cpp_gen2.casu", manifest, chunks, 2);
        mine1 = read_file(dir + "/cpp_gen1.casu");
        mine2 = read_file(dir + "/cpp_gen2.casu");
    } catch (const CasuError& exc) {
        write_ok = false;
        std::printf("  write error: %s\n", exc.what());
    }
    check(write_ok, "c++ writer runs");

    const std::string ref1 = read_file(gen1_path);
    const std::string ref2 = read_file(gen2_path);
    if (mine1 != ref1) {
        for (std::size_t i = 0; i < std::min(mine1.size(), ref1.size()); ++i) {
            if (mine1[i] != ref1[i]) {
                std::printf("  first diff at byte %zu: cpp=%02x py=%02x\n", i,
                            uint8_t(mine1[i]), uint8_t(ref1[i]));
                break;
            }
        }
    }
    check(mine1.size() == ref1.size(), "gen1 size parity");
    check(mine1 == ref1, "gen1 BYTE-IDENTICAL to python output");
    check(mine2 == ref2, "gen2 BYTE-IDENTICAL to python output");

    // --- 3. Round-trip: C++ written file re-reads cleanly ------------------
    bool roundtrip_ok = true;
    try {
        const casunat2::Container back =
            casunat2::read_native_v2(dir + "/cpp_gen1.casu");
        roundtrip_ok = back.chunks.size() == 12 && back.integrity_verified;
        const natv2::CanonicalFrame frame =
            casunat2::reconstruct_video(back, 1, 0);
        roundtrip_ok = roundtrip_ok &&
                       frame.digest() ==
                           "558cacc23a3818c928d4ffd1a098b5119eabb599dd726277d26229050568f4c8";
    } catch (const CasuError& exc) {
        roundtrip_ok = false;
        std::printf("  roundtrip error: %s\n", exc.what());
    }
    check(roundtrip_ok, "c++ file round-trips through strict reader");

    // --- 4. Recover / repair on a truncated copy ---------------------------
    const std::string truncated_path = dir + "/truncated.casu";
    const std::string repaired_path = dir + "/repaired.casu";
    write_file(truncated_path, ref2.substr(0, 1700));  // mid-tile2, after first RECOVERY_POINT
    bool recover_ok = true;
    std::string repaired_bytes;
    try {
        const casunat2::NativeV2Recovery recovery =
            casunat2::recover_native_v2(truncated_path);
        casunat2::repair_native_v2(truncated_path, repaired_path);
        repaired_bytes = read_file(repaired_path);
        // The repaired manifest must carry the recovery marker.
        const casunat2::Container rc =
            casunat2::read_native_v2(repaired_path);
        recover_ok = recovery.complete_chunk_offset > 0 &&
                     rc.manifest.find("recovery") != nullptr &&
                     !rc.manifest.find("recovery")
                          ->as_object()
                          .items.empty();
    } catch (const CasuError& exc) {
        recover_ok = false;
        std::printf("  recovery error: %s\n", exc.what());
    }
    check(recover_ok, "recover+repair produces a valid prefix file");
    check(!repaired_bytes.empty() &&
              Sha256::oneshot(repaired_bytes).size() == 64,
        "repaired file has digest");

    // --- 5. Fail-closed rejections -----------------------------------------
    // Duplicate JSON keys in the manifest are rejected.
    bool dup_rejected = false;
    {
        auto root = std::make_shared<JsonObject>();
        // Build raw bytes with duplicate key by hand.
        std::string dup_manifest = R"({"format":"CASUNAT2","version":2,)"
                                   R"("format":"CASUNAT2","streams":[]})";
        try {
            parse_strict_json(dup_manifest);
        } catch (const JsonError&) {
            dup_rejected = true;
        }
    }
    check(dup_rejected, "duplicate JSON keys rejected");

    // Integer overflow rejected instead of clamped.
    bool overflow_rejected = false;
    try {
        parse_strict_json("{\"v\": 99999999999999999999999}");
    } catch (const JsonError&) {
        overflow_rejected = true;
    }
    check(overflow_rejected, "integer overflow rejected");

    // Unpaired surrogate escape rejected.
    bool surrogate_rejected = false;
    try {
        parse_strict_json("{\"v\": \"\\ud83d\"}");
    } catch (const JsonError&) {
        surrogate_rejected = true;
    }
    check(surrogate_rejected, "unpaired surrogate rejected");

    // Valid surrogate pair accepted.
    bool pair_accepted = false;
    try {
        const JsonValue v = parse_strict_json("{\"v\": \"\\ud83d\\ude00\"}");
        pair_accepted = v.find("v")->as_string() == "\xF0\x9F\x98\x80";
    } catch (const JsonError&) {
        pair_accepted = false;
    }
    check(pair_accepted, "surrogate pair accepted");

    // ensure_ascii escaping matches json.dumps.
    {
        auto o = std::make_shared<JsonObject>();
        o->items["k"] = JsonValue(std::string("\xC3\xA4"));
        check(dump_json(JsonValue(o), true, true) == "{\"k\":\"\\u00e4\"}",
              "ensure_ascii escaping");
        check(dump_json(JsonValue(o), true, false) ==
                  std::string("{\"k\":\"\xC3\xA4\"}"),
              "ensure_ascii=False passthrough");
    }

    if (failures == 0) std::printf("ALL PASS (%d checks)\n", checks);
    else std::printf("%d/%d FAILED\n", failures, checks);
    return failures == 0 ? 0 : 1;
}
