"""Backend contract guidance for MPCASU."""
from __future__ import annotations
from typing import Protocol, Iterable

class MediaBackend(Protocol):
    def open(self, source) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    def seek(self, seconds: float) -> None: ...
    def position(self) -> float: ...
    def duration(self) -> float: ...
    def audio_tracks(self) -> Iterable[object]: ...
    def video_tracks(self) -> Iterable[object]: ...
    def subtitle_tracks(self) -> Iterable[object]: ...
    def chapters(self) -> Iterable[object]: ...
    def audio_devices(self) -> Iterable[object]: ...
    def close(self) -> None: ...

# Target implementations:
#   LibVLCBackend        -> all legacy sources supported by bundled/current libVLC
#   CasuCompatBackend    -> JSON sidecar / CASUNAT1 compatibility
#   NativeCasuBackend    -> CASUNAT2, no extraction and no libVLC inheritance
